### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by xen2** [SLaks/VSEmbed#3]
Thanks for the great work!
Just making sure, is the license MIT? (not visible in GitHub, but nuget License link was linking to MIT)

**Comment by SLaks** [comment]
Yes.

I should add that to the repo.

**Comment by JoshVarty** [comment]
👍 

I'm interested in using VSEmbed to profile the performance of different language services and their effects on the editor. I've forked since my goals are kind of orthogonal to the goals of this project (I've removed themes and will only take a dependency on VS 2017).

I'll be sure to commit back or advise on anything that might be useful to the main project itself.

**Comment by SLaks** [comment]
Thanks for the interest!

**Comment by SLaks** [comment]
@JoshVarty Then you'll probably also want to remove the VsMefContainerBuilder hackery & use https://www.nuget.org/packages/Microsoft.VisualStudio.Composition/ directly.

Actually, I should do that too, now that that's a public NuGet package.
